[versions]
activityComposeVersion = "1.8.2"
agp = "8.5.0"
arcgisMapsKotlin = "200.4.0"
auth = "1.2.3"
authVersion = "1.2.5"
composeBomVersion = "2023.10.01"
coreKtxVersion = "1.12.0"
esriArcgisMapsKotlin = "200.5.0-4309"
gson = "2.10.1"
gsonVersion = "2.6.1"
kotlin = "1.9.23"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.8.3"
activityCompose = "1.9.0"
composeBom = "2024.04.01"
lifecycleRuntimeKtxVersion = "2.8.4"
okhttp = "4.12.0"
playServicesAuth = "21.2.0"
spotifyAppRemoteRelease = "0.7.2"
appcompat = "1.7.0"

# ArcGIS Maps SDK for Kotlin version
arcgisMapsKotlinVersion = "200.5.0-4304"
# SDK versions
compileSdk = "34"
minSdk = "26"
targetSdk = "34"
versionCode = "2004000"
versionName = "200.4.0"
# Kotlin versions
kotlinVersion = "1.9.23"
ktxLifecycle = "2.7.0"
ktxFragmentsExt = "1.6.2"
ktxActivityExt = "1.9.0"
ktxAndroidCore = "1.13.0"
kotlinCompilerExt = "1.5.11"
# Compose versions
composeActivityVersion = "1.9.0"
composeBOM = "2024.04.01"
# Library versions
appcompatVersion = "1.6.1"
commonsIoVersion = "2.15.1"
constraintLayoutVersion = "2.1.4"
coordinateLayoutVersion = "1.2.0"
jsonSerialization = "1.6.3"
workVersion = "2.9.0"
multidexVersion = "2.0.1"
materialVersion = "1.11.0"
androidBrowserVersion = "1.8.0"
# Plugin versions
gradleVersion = "8.3.2"
playServicesMapsVersion = "19.0.0"
junitKtx = "1.2.1"
navigationRuntimeKtx = "2.7.7"
navigationCompose = "2.7.7"


[libraries]
androidx-activity-compose-v182 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-compose-bom-v20231001 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-lifecycle-runtime-ktx-v284 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
arcgis-maps-kotlin-v20040 = { module = "com.esri:arcgis-maps-kotlin", version.ref = "arcgisMapsKotlin" }
arcgis-maps-kotlin-v200504309 = { module = "com.esri:arcgis-maps-kotlin", version.ref = "esriArcgisMapsKotlin" }
auth = { module = "com.spotify.android:auth", version.ref = "auth" }
com-esri-arcgis-maps-kotlin-toolkit-geoview-compose = { module = "com.esri:arcgis-maps-kotlin-toolkit-geoview-compose" }
esri-arcgis-maps-kotlin-toolkit-geoview-compose = { module = "com.esri:arcgis-maps-kotlin-toolkit-geoview-compose", version.ref = "arcgisMapsKotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
material3 = { module = "androidx.compose.material3:material3" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
spotify-app-remote-release = { module = "com.spotify.android:spotify-app-remote-release", version.ref = "spotifyAppRemoteRelease" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion"}
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion"}
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivityVersion"}
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "ktxActivityExt"}
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidBrowserVersion"}
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBOM"}
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayoutVersion"}
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinateLayoutVersion"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktxAndroidCore"}
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "ktxFragmentsExt" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "ktxLifecycle"}
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "ktxLifecycle"}
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "ktxLifecycle"}
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "ktxLifecycle"}
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidexVersion"}
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workVersion" }
arcgis-maps-kotlin = { group = "com.esri", name = "arcgis-maps-kotlin", version.ref = "arcgisMapsKotlinVersion"}
arcgis-maps-kotlin-toolkit-bom = { group = "com.esri", name = "arcgis-maps-kotlin-toolkit-bom", version.ref = "arcgisMapsKotlinVersion"}
arcgis-maps-kotlin-toolkit-authentication = { group = "com.esri", name = "arcgis-maps-kotlin-toolkit-authentication" }
arcgis-maps-kotlin-toolkit-geoview-compose = { group = "com.esri", name = "arcgis-maps-kotlin-toolkit-geoview-compose" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsIoVersion" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "jsonSerialization" }
stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlinVersion"}
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMapsVersion" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
ui = { module = "androidx.compose.ui:ui" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }


[plugins]
android-application = { id = "com.android.application", version.ref = "gradleVersion" }
android-library = { id = "com.android.library", version.ref = "gradleVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

